services:
  app1:
    build:
      context: ./app1
      args:
        CACHEBUST: ${CACHEBUST:-1}
    ports:
      - "5001:5001"

  app2:
    build:
      context: ./app2
      args:
        CACHEBUST: ${CACHEBUST:-1}
    ports:
      - "5002:5002"
