version: "3.9"

services:
  app1:
    build:
      context: ./app1
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "5001:5001"
    restart: unless-stopped

  app2:
    build:
      context: ./app2
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "5002:5002"
    restart: unless-stopped
